### ISSUE TITLE
Is it possible to have the data not normalized ?

### ISSUE THREAD

**Issue by andompesta** [HKUST-KnowComp/MLMA_hate_speech#1]
Hi,

I'm wandering if it is possible to have the data WITH the stopwords. According to the annotated_data_processing.py code you have remove all the english stopwords. Is it possible to have the english data with all the stopwords ?

Cheers,
Sandro

**Comment by nedjmaou** [comment]
Hi Sandro, 

Thank you for reporting this issue. I have just uploaded the English data with all the stop words. In hate_speech_mlma.zip you will find the file en_dataset_with_stopwords.csv .

Best, 
Nedjma.

**Comment by nedjmaou** [comment]
Hi Sandro,

Thank you for reporting this issue. I have just uploaded the English data with all the stop words (en_dataset_with_stopwords.csv in hate_speech_mlma.zip).

Best,
Nedjma.
