### ISSUE TITLE
Huggingface Datasets support?

### ISSUE THREAD

**Issue by thesofakillers** [HKUST-KnowComp/MLMA_hate_speech#2]
Hi, thank you for your work.

Any plans to share your dataset via the huggingface datasets hub?

**Comment by nedjmaou** [comment]
Hi @thesofakillers, 

Thanks for reaching out. I will post an update whenever it is available.

**Comment by nedjmaou** [comment]
Hi @thesofakillers, the dataset is now available on HuggingFace (https://huggingface.co/datasets/nedjmaou/MLMA_hate_speech)). [Sorry for the delay!]
